// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// ADSSModC
List ADSSModC(const List& parameters_arg);
RcppExport SEXP _MedianaDesigner_ADSSModC(SEXP parameters_argSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type parameters_arg(parameters_argSEXP);
    rcpp_result_gen = Rcpp::wrap(ADSSModC(parameters_arg));
    return rcpp_result_gen;
END_RCPP
}
// ADTreatSelC
List ADTreatSelC(const List& parameters_arg);
RcppExport SEXP _MedianaDesigner_ADTreatSelC(SEXP parameters_argSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type parameters_arg(parameters_argSEXP);
    rcpp_result_gen = Rcpp::wrap(ADTreatSelC(parameters_arg));
    return rcpp_result_gen;
END_RCPP
}
// ADPopSelC
List ADPopSelC(const List& parameters_arg);
RcppExport SEXP _MedianaDesigner_ADPopSelC(SEXP parameters_argSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type parameters_arg(parameters_argSEXP);
    rcpp_result_gen = Rcpp::wrap(ADPopSelC(parameters_arg));
    return rcpp_result_gen;
END_RCPP
}
// FutRuleC
List FutRuleC(const List& parameters_arg);
RcppExport SEXP _MedianaDesigner_FutRuleC(SEXP parameters_argSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type parameters_arg(parameters_argSEXP);
    rcpp_result_gen = Rcpp::wrap(FutRuleC(parameters_arg));
    return rcpp_result_gen;
END_RCPP
}
// EventPredEventCount
List EventPredEventCount(const List& parameters_arg);
RcppExport SEXP _MedianaDesigner_EventPredEventCount(SEXP parameters_argSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type parameters_arg(parameters_argSEXP);
    rcpp_result_gen = Rcpp::wrap(EventPredEventCount(parameters_arg));
    return rcpp_result_gen;
END_RCPP
}
// ADRandC
List ADRandC(const List& parameters_arg);
RcppExport SEXP _MedianaDesigner_ADRandC(SEXP parameters_argSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type parameters_arg(parameters_argSEXP);
    rcpp_result_gen = Rcpp::wrap(ADRandC(parameters_arg));
    return rcpp_result_gen;
END_RCPP
}
// MultAdjC1
List MultAdjC1(const List& parameters_arg);
RcppExport SEXP _MedianaDesigner_MultAdjC1(SEXP parameters_argSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type parameters_arg(parameters_argSEXP);
    rcpp_result_gen = Rcpp::wrap(MultAdjC1(parameters_arg));
    return rcpp_result_gen;
END_RCPP
}
// MultAdjC2
List MultAdjC2(const List& parameters_arg);
RcppExport SEXP _MedianaDesigner_MultAdjC2(SEXP parameters_argSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type parameters_arg(parameters_argSEXP);
    rcpp_result_gen = Rcpp::wrap(MultAdjC2(parameters_arg));
    return rcpp_result_gen;
END_RCPP
}
// MultAdjC3
List MultAdjC3(const List& parameters_arg);
RcppExport SEXP _MedianaDesigner_MultAdjC3(SEXP parameters_argSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type parameters_arg(parameters_argSEXP);
    rcpp_result_gen = Rcpp::wrap(MultAdjC3(parameters_arg));
    return rcpp_result_gen;
END_RCPP
}
// ClustRandGEEC
List ClustRandGEEC(const List& parameters_arg);
RcppExport SEXP _MedianaDesigner_ClustRandGEEC(SEXP parameters_argSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type parameters_arg(parameters_argSEXP);
    rcpp_result_gen = Rcpp::wrap(ClustRandGEEC(parameters_arg));
    return rcpp_result_gen;
END_RCPP
}
// ExportTradMultAdj
NumericVector ExportTradMultAdj(const int& test, const NumericVector& pvalue, const NumericVector& weight, const NumericVector& transition);
RcppExport SEXP _MedianaDesigner_ExportTradMultAdj(SEXP testSEXP, SEXP pvalueSEXP, SEXP weightSEXP, SEXP transitionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int& >::type test(testSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type pvalue(pvalueSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type weight(weightSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type transition(transitionSEXP);
    rcpp_result_gen = Rcpp::wrap(ExportTradMultAdj(test, pvalue, weight, transition));
    return rcpp_result_gen;
END_RCPP
}
// ExportRandomClusterSize
IntegerVector ExportRandomClusterSize(const int& sample_size, const NumericVector& proportion);
RcppExport SEXP _MedianaDesigner_ExportRandomClusterSize(SEXP sample_sizeSEXP, SEXP proportionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int& >::type sample_size(sample_sizeSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type proportion(proportionSEXP);
    rcpp_result_gen = Rcpp::wrap(ExportRandomClusterSize(sample_size, proportion));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MedianaDesigner_ADSSModC", (DL_FUNC) &_MedianaDesigner_ADSSModC, 1},
    {"_MedianaDesigner_ADTreatSelC", (DL_FUNC) &_MedianaDesigner_ADTreatSelC, 1},
    {"_MedianaDesigner_ADPopSelC", (DL_FUNC) &_MedianaDesigner_ADPopSelC, 1},
    {"_MedianaDesigner_FutRuleC", (DL_FUNC) &_MedianaDesigner_FutRuleC, 1},
    {"_MedianaDesigner_EventPredEventCount", (DL_FUNC) &_MedianaDesigner_EventPredEventCount, 1},
    {"_MedianaDesigner_ADRandC", (DL_FUNC) &_MedianaDesigner_ADRandC, 1},
    {"_MedianaDesigner_MultAdjC1", (DL_FUNC) &_MedianaDesigner_MultAdjC1, 1},
    {"_MedianaDesigner_MultAdjC2", (DL_FUNC) &_MedianaDesigner_MultAdjC2, 1},
    {"_MedianaDesigner_MultAdjC3", (DL_FUNC) &_MedianaDesigner_MultAdjC3, 1},
    {"_MedianaDesigner_ClustRandGEEC", (DL_FUNC) &_MedianaDesigner_ClustRandGEEC, 1},
    {"_MedianaDesigner_ExportTradMultAdj", (DL_FUNC) &_MedianaDesigner_ExportTradMultAdj, 4},
    {"_MedianaDesigner_ExportRandomClusterSize", (DL_FUNC) &_MedianaDesigner_ExportRandomClusterSize, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_MedianaDesigner(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
