// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// ADSSModC
List ADSSModC(const List& parameters_arg);
RcppExport SEXP _MedianaDesigner_ADSSModC(SEXP parameters_argSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type parameters_arg(parameters_argSEXP);
    rcpp_result_gen = Rcpp::wrap(ADSSModC(parameters_arg));
    return rcpp_result_gen;
END_RCPP
}
// ADTreatSelC
List ADTreatSelC(const List& parameters_arg);
RcppExport SEXP _MedianaDesigner_ADTreatSelC(SEXP parameters_argSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type parameters_arg(parameters_argSEXP);
    rcpp_result_gen = Rcpp::wrap(ADTreatSelC(parameters_arg));
    return rcpp_result_gen;
END_RCPP
}
// ADPopSelC
List ADPopSelC(const List& parameters_arg);
RcppExport SEXP _MedianaDesigner_ADPopSelC(SEXP parameters_argSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type parameters_arg(parameters_argSEXP);
    rcpp_result_gen = Rcpp::wrap(ADPopSelC(parameters_arg));
    return rcpp_result_gen;
END_RCPP
}
// FutRuleC
List FutRuleC(const List& parameters_arg);
RcppExport SEXP _MedianaDesigner_FutRuleC(SEXP parameters_argSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type parameters_arg(parameters_argSEXP);
    rcpp_result_gen = Rcpp::wrap(FutRuleC(parameters_arg));
    return rcpp_result_gen;
END_RCPP
}
// EventPredEventCount
List EventPredEventCount(const List& parameters_arg);
RcppExport SEXP _MedianaDesigner_EventPredEventCount(SEXP parameters_argSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type parameters_arg(parameters_argSEXP);
    rcpp_result_gen = Rcpp::wrap(EventPredEventCount(parameters_arg));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MedianaDesigner_ADSSModC", (DL_FUNC) &_MedianaDesigner_ADSSModC, 1},
    {"_MedianaDesigner_ADTreatSelC", (DL_FUNC) &_MedianaDesigner_ADTreatSelC, 1},
    {"_MedianaDesigner_ADPopSelC", (DL_FUNC) &_MedianaDesigner_ADPopSelC, 1},
    {"_MedianaDesigner_FutRuleC", (DL_FUNC) &_MedianaDesigner_FutRuleC, 1},
    {"_MedianaDesigner_EventPredEventCount", (DL_FUNC) &_MedianaDesigner_EventPredEventCount, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_MedianaDesigner(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
