# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ADSSModC <- function(parameters_arg) {
    .Call(`_MedianaDesigner_ADSSModC`, parameters_arg)
}

ADTreatSelC <- function(parameters_arg) {
    .Call(`_MedianaDesigner_ADTreatSelC`, parameters_arg)
}

ADPopSelC <- function(parameters_arg) {
    .Call(`_MedianaDesigner_ADPopSelC`, parameters_arg)
}

FutRuleC <- function(parameters_arg) {
    .Call(`_MedianaDesigner_FutRuleC`, parameters_arg)
}

EventPredEventCount <- function(parameters_arg) {
    .Call(`_MedianaDesigner_EventPredEventCount`, parameters_arg)
}

ADRandC <- function(parameters_arg) {
    .Call(`_MedianaDesigner_ADRandC`, parameters_arg)
}

MultAdjC1 <- function(parameters_arg) {
    .Call(`_MedianaDesigner_MultAdjC1`, parameters_arg)
}

MultAdjC2 <- function(parameters_arg) {
    .Call(`_MedianaDesigner_MultAdjC2`, parameters_arg)
}

MultAdjC3 <- function(parameters_arg) {
    .Call(`_MedianaDesigner_MultAdjC3`, parameters_arg)
}

